---
product:
  name: onlyoffice

persistence:
  existingClaim: ""
  storageClass: "nfs"
  size: 8Gi
  
example:
  ### Enter your doc.service address for example http://10.0.0.1/ 
  dsUrl: http://onlyoffice-docs-address/
  replicas: 1
  containerImage: onlyoffice/docs-example:latest
  imagePullPolicy: IfNotPresent
  resources:
    ##Example:
    ##requests:
    ##  memory: "128Mi"
    ##  cpu: "100m"
    requests: {}
    ##limits:
    ##  memory: "128Mi"
    ##  cpu: "250m"
    limits: {}

service:
  ### Enter the address to access the example service 
  externalIP:    

jwt:
  enabled: false
  secret: MYSECRET
  header: Authorization
  inBody: false

securityContext:
  enabled: false
  example:
    runAsUser: 1001
    runAsGroup: 1001
