---
kind: Service
apiVersion: v1
metadata:
  name: example-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: example
  type: LoadBalancer
  externalIPs:
    - {{ .Values.service.externalIP }}
