---
kind: Service
apiVersion: v1
metadata:
  name: example
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: example
  type: {{ .Value.service.type }}
