---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: examplepvc
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
